server:
  port: 8888
  servlet:
    context-path: /petdoc

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/db_pet?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update  # 后面用update
    show-sql: true